---
swagger: '2.0'
basePath: "/"
paths:
  "/announcements":
    get:
      responses:
        '200':
          description: Success
      operationId: get_announcements
      tags:
      - default
  "/attendance/":
    get:
      responses:
        '200':
          description: Success
      operationId: get_attendance
      tags:
      - default
  "/attendance/details/{detail_url}":
    parameters:
    - name: detail_url
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_attendance_detail
      tags:
      - default
  "/grades/{sort_by}":
    parameters:
    - name: sort_by
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      summary: 'Returns a dictionary containing Grades and GPA (Average Grades) {"Grades": '
      description: |-
        , "Gpa": ...}
        Grades values contain both semesters as dictionaries inside a list [{"Biology": [...], [...]}, {"Biology": [...], [...]}]
        Each subject inside a semester contains a list of all grades. A grade is a dictionary with all the grade attributes.
        Gpa values contain a dictionary with Subject names as keys and a list of semesters avg. and final avg.
        GPA structure: {
                "Biology": [{"gpa": 3.0}, {"gpa": 4.3}],
                "History": [{"gpa: 2.1"}, {"gpa": 1.2}],
                }
        Grades structure: [
                { # First Semester
                    "Biology": [dicts of grades],
                    "History": [dicts of grades],
                    ...
                    },
                { # Second Semester
                    "Biology": [dicts of grades],
                    ...
                    }
                ]
      operationId: get_grades
      tags:
      - default
  "/homework/details/{detail_url}":
    parameters:
    - name: detail_url
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_homework_details
      tags:
      - default
  "/homework/{date_from}/{date_to}":
    parameters:
    - name: date_from
      in: path
      required: true
      type: string
    - name: date_to
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_homework
      tags:
      - default
  "/login":
    post:
      responses:
        '200':
          description: Success
      operationId: post_login
      parameters:
      - name: payload
        required: true
        in: body
        schema:
          "$ref": "#/definitions/Login"
      tags:
      - default
  "/messages/content/{content_url}":
    parameters:
    - name: content_url
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_message_content
      tags:
      - default
  "/messages/pages":
    get:
      responses:
        '200':
          description: Success
          headers:
            X-API-Key:
              type: array
              items:
                type: string
      operationId: get_message_pages
      tags:
      - default
  "/messages/{page}":
    parameters:
    - name: page
      in: path
      required: true
      type: integer
    get:
      responses:
        '200':
          description: Success
          headers:
            X-API-Key:
              type: array
              items:
                type: string
      operationId: get_message
      tags:
      - default
  "/overview":
    post:
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/Overview"
      operationId: post_overview
      tags:
      - default
  "/schedule/details/{detail_prefix}/{detail_url}":
    parameters:
    - name: detail_prefix
      in: path
      required: true
      type: string
    - name: detail_url
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_schedule_detail
      tags:
      - default
  "/schedule/{year}/{month}":
    parameters:
    - name: year
      in: path
      required: true
      type: string
    - name: month
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_schedule
      tags:
      - default
  "/timetable/{year}/{month}/{day}":
    parameters:
    - name: year
      in: path
      required: true
      type: string
    - name: month
      in: path
      required: true
      type: string
    - name: day
      in: path
      required: true
      type: string
    get:
      responses:
        '200':
          description: Success
      operationId: get_timetable
      tags:
      - default
info:
  title: API
  version: '1.0'
produces:
- application/json
consumes:
- application/json
tags:
- name: default
  description: Default namespace
definitions:
  Login:
    properties:
      username:
        type: string
      password:
        type: string
    type: object
  Overview:
    properties:
      last_login_date:
        type: string
      last_login_time:
        type: string
    type: object
responses:
  ParseError:
    description: When a mask can't be parsed
  MaskError:
    description: When any error occurs on mask
